import Head from "next/head";
import Header from "../components/Header";

type Props = {
	children?: React.ReactNode;
};

export default function PageLayout({ children }: Props) {
	return (
		<div className='relative'>
			<div className='absolute inset-0 w-full h-full bg-pattern-bir bg-repeat bg-center opacity-40'></div>
			{/* <div className='absolute inset-0 w-full h-full bg-pattern-1 bg-repeat bg-center opacity-50'></div> */}

			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<main className='relative'>{children}</main>
		</div>
	);
}
