import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import { BOSS_TYPES } from "../config";
import PageLayout from "../layouts/pageLayout";
import RadioGroupUI from "../components/RadioGroupUI";

/**
 * TODO FEATURES:
 * - select a boss buttons
 *   - shine hover effect
 *   - more info on boss
 *   - save selected boss in session
 *   - animate buttons cascading grid
 *   - animating gradient border on selected boss
 *   - use headlessUI
 * - boss respawn timer
 *   - use headlessUI tabs
 * - timer history list
 *   - states: respawned (strikethrough), to respawn
 * - alert mode when boss is respawning
 * - sound notification when respawning
 * - convert how to use to a whole page modal
 * - add option to use discord webhook
 *   - add instruction how
 * - add next boss panel, add countdown
 */

const container = {
	hidden: { opacity: 1, scale: 0 },
	visible: {
		opacity: 1,
		scale: 1,
		transition: {
			delayChildren: 0.3,
			staggerChildren: 0.075,
		},
	},
};

const item = {
	hidden: { y: 20, opacity: 0 },
	visible: {
		y: 0,
		opacity: 1,
	},
	hover: {
		y: 8,
	},
};

const textMotion = {
	hover: {
		scale: 1.2,
		transition: {
			duration: 0.2,
		},
	},
};

export default function Home() {
	return (
		<PageLayout>
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<section className='px-4 sm:px-8 container mx-auto'>
					<RadioGroupUI />
				</section>

				<div className='px-4 sm:px-8 container mx-auto'>
					<h2 className='my-8 text-4xl'>Step 1. Select a boss</h2>
					<motion.div
						variants={container}
						initial='hidden'
						animate='visible'
						className='w-full inline-grid grid-flow-row grid-cols-1 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-6 grid-rows-3 gap-6'
					>
						{/* hover:outline hover:outline-4 hover:outline-indigo-400 */}
						{BOSS_TYPES.map((boss, index) => (
							<motion.button
								variants={item}
								className='group relative overflow-hidden hover:cursor-pointer  duration-150 p-2 rounded-lg sm:rounded-2xl text-center grid place-content-center w-full sm:aspect-[4/3] bg-bir-red hover:bg-bir-red-light shadow-bottom-red border-bir-red-dark'
								key={index}
							>
								<div className='absolute top-0 -inset-full h-full w-1/2 z-5 block transform -skew-x-12 bg-gradient-to-r from-transparent to-white opacity-40 group-hover:animate-shine' />
								<span className='text-xl lg:text-2xl xl:lg:text-3xl tracking-wide'>
									{boss.name}
								</span>
							</motion.button>
						))}
					</motion.div>
				</div>

				<main className={styles.main}>
					<h1 className={styles.title}>
						Welcome to <a href='https://nextjs.org'>Next.js!</a>
					</h1>

					<p className={styles.description}>
						Get started by editing{" "}
						<code className={styles.code}>pages/index.tsx</code>
					</p>

					<div className={styles.grid}>
						<a href='https://nextjs.org/docs' className={styles.card}>
							<h2>Documentation &rarr;</h2>
							<p>Find in-depth information about Next.js features and API.</p>
						</a>

						<a href='https://nextjs.org/learn' className={styles.card}>
							<h2>Learn &rarr;</h2>
							<p>Learn about Next.js in an interactive course with quizzes!</p>
						</a>

						<a
							href='https://github.com/vercel/next.js/tree/canary/examples'
							className={styles.card}
						>
							<h2>Examples &rarr;</h2>
							<p>Discover and deploy boilerplate example Next.js projects.</p>
						</a>

						<a
							href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
							className={styles.card}
						>
							<h2>Deploy &rarr;</h2>
							<p>
								Instantly deploy your Next.js site to a public URL with Vercel.
							</p>
						</a>
					</div>
				</main>

				<footer className={styles.footer}>
					<a
						href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						target='_blank'
						rel='noopener noreferrer'
					>
						Powered by{" "}
						<span className={styles.logo}>
							<Image
								src='/vercel.svg'
								alt='Vercel Logo'
								width={72}
								height={16}
							/>
						</span>
					</a>
				</footer>
			</div>
		</PageLayout>
	);
}
